- name: Update Goapp Application
  command: "go get -u {{ appsrc }}"
  environment:
    PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/go/bin
    GOPATH: /opt/go-src
  notify: goapp restart
